// Auto-generated by napi-mbt generator. DO NOT EDIT.

export function add(a: number, b: number): number;
export function concat(a: string, b: string): string;
export function mutate_buffer(view: Buffer): void;
export function roundtrip_bytes(b: Buffer): Buffer;
export function check_bool(b: boolean): boolean;
export function check_bool(b: boolean): boolean;
export function check_double(d: number): number;
