/* Auto-generated by napi-mbt. DO NOT EDIT. */
#include <node_api.h>
#include <stddef.h>
#include <stdint.h>

extern void moonbit_init(void);
extern napi_value napi_mbt_adapter_add(napi_env env, napi_value, napi_value);
extern napi_value napi_mbt_adapter_check_bool(napi_env env, napi_value);
extern napi_value napi_mbt_adapter_check_double(napi_env env, napi_value);
extern napi_value napi_mbt_adapter_concat(napi_env env, napi_value, napi_value);
extern napi_value napi_mbt_adapter_mutate_buffer(napi_env env, napi_value);
extern napi_value napi_mbt_adapter_roundtrip_bytes(napi_env env, napi_value);

static napi_value napi_mbt_callback_add(napi_env env, napi_callback_info info) {
  size_t argc = 2;
  napi_value argv[2];
  napi_status status = napi_get_cb_info(env, info, &argc, argv, NULL, NULL);
  if (status != napi_ok) return NULL;
  if (argc < 2) { napi_throw_error(env, NULL, "Missing argument"); return NULL; }
  return napi_mbt_adapter_add(env, argv[0], argv[1]);
}

static napi_value napi_mbt_callback_check_bool(napi_env env, napi_callback_info info) {
  size_t argc = 1;
  napi_value argv[1];
  napi_status status = napi_get_cb_info(env, info, &argc, argv, NULL, NULL);
  if (status != napi_ok) return NULL;
  if (argc < 1) { napi_throw_error(env, NULL, "Missing argument"); return NULL; }
  return napi_mbt_adapter_check_bool(env, argv[0]);
}

static napi_value napi_mbt_callback_check_double(napi_env env, napi_callback_info info) {
  size_t argc = 1;
  napi_value argv[1];
  napi_status status = napi_get_cb_info(env, info, &argc, argv, NULL, NULL);
  if (status != napi_ok) return NULL;
  if (argc < 1) { napi_throw_error(env, NULL, "Missing argument"); return NULL; }
  return napi_mbt_adapter_check_double(env, argv[0]);
}

static napi_value napi_mbt_callback_concat(napi_env env, napi_callback_info info) {
  size_t argc = 2;
  napi_value argv[2];
  napi_status status = napi_get_cb_info(env, info, &argc, argv, NULL, NULL);
  if (status != napi_ok) return NULL;
  if (argc < 2) { napi_throw_error(env, NULL, "Missing argument"); return NULL; }
  return napi_mbt_adapter_concat(env, argv[0], argv[1]);
}

static napi_value napi_mbt_callback_mutate_buffer(napi_env env, napi_callback_info info) {
  size_t argc = 1;
  napi_value argv[1];
  napi_status status = napi_get_cb_info(env, info, &argc, argv, NULL, NULL);
  if (status != napi_ok) return NULL;
  if (argc < 1) { napi_throw_error(env, NULL, "Missing argument"); return NULL; }
  return napi_mbt_adapter_mutate_buffer(env, argv[0]);
}

static napi_value napi_mbt_callback_roundtrip_bytes(napi_env env, napi_callback_info info) {
  size_t argc = 1;
  napi_value argv[1];
  napi_status status = napi_get_cb_info(env, info, &argc, argv, NULL, NULL);
  if (status != napi_ok) return NULL;
  if (argc < 1) { napi_throw_error(env, NULL, "Missing argument"); return NULL; }
  return napi_mbt_adapter_roundtrip_bytes(env, argv[0]);
}

#if defined(_WIN32)
#define NAPI_MBT_EXPORT __declspec(dllexport)
#else
#define NAPI_MBT_EXPORT __attribute__((visibility("default")))
#endif

NAPI_MBT_EXPORT napi_value napi_register_module_v1(napi_env env, napi_value exports) {
  moonbit_init();
  napi_value fn_add;
  napi_create_function(env, "add", NAPI_AUTO_LENGTH, napi_mbt_callback_add, NULL, &fn_add);
  napi_set_named_property(env, exports, "add", fn_add);
  napi_value fn_check_bool;
  napi_create_function(env, "check_bool", NAPI_AUTO_LENGTH, napi_mbt_callback_check_bool, NULL, &fn_check_bool);
  napi_set_named_property(env, exports, "check_bool", fn_check_bool);
  napi_value fn_check_double;
  napi_create_function(env, "check_double", NAPI_AUTO_LENGTH, napi_mbt_callback_check_double, NULL, &fn_check_double);
  napi_set_named_property(env, exports, "check_double", fn_check_double);
  napi_value fn_concat;
  napi_create_function(env, "concat", NAPI_AUTO_LENGTH, napi_mbt_callback_concat, NULL, &fn_concat);
  napi_set_named_property(env, exports, "concat", fn_concat);
  napi_value fn_mutate_buffer;
  napi_create_function(env, "mutate_buffer", NAPI_AUTO_LENGTH, napi_mbt_callback_mutate_buffer, NULL, &fn_mutate_buffer);
  napi_set_named_property(env, exports, "mutate_buffer", fn_mutate_buffer);
  napi_value fn_roundtrip_bytes;
  napi_create_function(env, "roundtrip_bytes", NAPI_AUTO_LENGTH, napi_mbt_callback_roundtrip_bytes, NULL, &fn_roundtrip_bytes);
  napi_set_named_property(env, exports, "roundtrip_bytes", fn_roundtrip_bytes);
  return exports;
}
