const fs = require('fs');
const path = require('path');
const webTreeSitter = require('web-tree-sitter');
const Parser = webTreeSitter.Parser || webTreeSitter;
const Language = webTreeSitter.Language || Parser.Language;

const args = process.argv.slice(2);
const isCheck = args.includes('--check');
let pkgDir = args.find(a => !a.startsWith('--')) || '.';

async function main() {
  await Parser.init();
  const parser = new Parser();
  const wasmPath = path.resolve(__dirname, '../node_modules/tree-sitter-moonbit/tree-sitter-moonbit.wasm');
  const MoonBit = await Language.load(wasmPath);
  parser.setLanguage(MoonBit);

  const files = fs.readdirSync(pkgDir).filter(f => f.endsWith('.mbt') && !f.endsWith('_test.mbt') && !f.endsWith('_wbtest.mbt') && f !== '_napi_bindings.mbt');
  
  let hasErrors = false;
  let bindingsMbt = `// Auto-generated by napi-mbt generator. DO NOT EDIT.\n\n`;
  let dts = `// Auto-generated by napi-mbt generator. DO NOT EDIT.\n\n`;
  
  let dispatcherCode = `pub fn moonbit_napi_dispatcher(func_id : Int, env : NapiEnv, info : NapiCallbackInfo) -> NapiValue {\n  match func_id {\n`;
  
  let funcId = 0;
  const exportedFuncs = [];

  for (const file of files) {
    const filePath = path.join(pkgDir, file);
    const code = fs.readFileSync(filePath, 'utf-8');
    const tree = parser.parse(code);
    const root = tree.rootNode;
    
    if (root.hasError) {
      console.error(`[ERROR] File ${file} has syntax errors.`);
      hasErrors = true;
      continue;
    }

    for (let i = 0; i < root.childCount; i++) {
      const node = root.child(i);
      if (node.type === 'comment' && node.text.trim() === '/// @napi') {
        let nextIdx = i + 1;
        while (nextIdx < root.childCount && (root.child(nextIdx)?.type === 'comment' || root.child(nextIdx)?.type === 'semicolon')) {
            nextIdx++;
        }
        
        let structItem = root.child(nextIdx);
        let funcNode = structItem;
        if (structItem && structItem.type === 'structure_item') {
          funcNode = structItem.child(0);
        }
        
        if (!funcNode || funcNode.type !== 'function_definition') {
          console.error(`[ERROR] ${file}:${node.startPosition.row + 1}: /// @napi is not followed by a function definition.`);
          hasErrors = true;
          continue;
        }

        const isPub = funcNode.children.some(c => c.type === 'visibility' || c.text === 'pub');
        if (!isPub) {
          console.error(`[ERROR] ${file}:${funcNode.startPosition.row + 1}: /// @napi functions must be pub.`);
          hasErrors = true;
          continue;
        }

        const nameNode = funcNode.children.find(c => c.type === 'function_identifier' || c.type === 'identifier');
        const paramsNode = funcNode.children.find(c => c.type === 'parameters');
        const retNode = funcNode.children.find(c => c.type === 'return_type');

        if (!nameNode || !paramsNode) {
          console.error(`[ERROR] ${file}:${funcNode.startPosition.row + 1}: Invalid function signature.`);
          hasErrors = true;
          continue;
        }

        const funcName = nameNode.text;
        
        const params = [];
        for (const p of paramsNode.children) {
          if (p.type === 'parameter') {
            const pText = p.text;
            const parts = pText.split(':').map(s => s.trim());
            if (parts.length >= 2) {
              params.push({name: parts[0], type: parts[1]});
            }
          }
        }

        if (params.length > 16) {
          console.error(`[ERROR] ${file}:${funcNode.startPosition.row + 1}: Function ${funcName} has more than 16 parameters.`);
          hasErrors = true;
          continue;
        }

        let retType = 'Unit';
        if (retNode) {
          // returns something like `-> Int!Error`
          retType = retNode.text.replace('->', '').trim().replace(/!.*$/, '').trim();
        }
        
        const throws = retNode ? retNode.text.includes('!') : false;

        const allowedParamTypes = ['Int', 'Double', 'Bool', 'String', 'Bytes', 'NapiBufferView'];
        const allowedRetTypes = ['Int', 'Double', 'Bool', 'String', 'Bytes', 'Unit'];
        
        let valid = true;
        for (const p of params) {
          if (!allowedParamTypes.includes(p.type)) {
            console.error(`[ERROR] ${file}:${funcNode.startPosition.row + 1}: Unsupported parameter type ${p.type} in ${funcName}.`);
            valid = false;
          }
        }
        if (!allowedRetTypes.includes(retType)) {
          console.error(`[ERROR] ${file}:${funcNode.startPosition.row + 1}: Unsupported return type ${retType} in ${funcName}.`);
          valid = false;
        }
        if (retType === 'NapiBufferView') {
          console.error(`[ERROR] ${file}:${funcNode.startPosition.row + 1}: Generator prohibits returning NapiBufferView in ${funcName}.`);
          valid = false;
        }

        if (!valid) {
          hasErrors = true;
          continue;
        }

        const id = funcId++;
        exportedFuncs.push({name: funcName, id});

        const wrapperName = `_napi_wrapper_${id}_${funcName}`;
        bindingsMbt += `\nfn ${wrapperName}(env : NapiEnv, info : NapiCallbackInfo) -> NapiValue {\n`;
        bindingsMbt += `  let argc = Ref(0)\n`;
        const argcArgs = Array.from({length: 16}, (_, idx) => `let a${idx} = Ref(moonbit_dummy_napi_value())`).join('\n  ');
        bindingsMbt += `  ${argcArgs}\n`;
        bindingsMbt += `  let status = moonbit_napi_get_cb_info_max(env, info, argc, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15)\n`;
        bindingsMbt += `  result_from_status(env, status, b"Failed to get arguments")\n`;

        const argsStr = params.map((p, idx) => {
          bindingsMbt += `  let p${idx} = match argc.val > ${idx} {\n`;
          bindingsMbt += `    true => get_${p.type}(env, a${idx}.val)\n`;
          bindingsMbt += `    false => { let _ = napi_throw_error(env, b"", b"Missing argument ${idx}"); return moonbit_dummy_napi_value() }\n`;
          bindingsMbt += `  }\n`;
          return `p${idx}`;
        }).join(', ');

        if (throws) {
          bindingsMbt += `  let res : ${retType} = try {\n`;
          bindingsMbt += `    ${funcName}!(${argsStr})\n`;
          bindingsMbt += `  } catch {\n`;
          bindingsMbt += `    e => { let _ = napi_throw_error(env, b"", @utf8.encode(e.to_string())); return moonbit_dummy_napi_value() }\n`;
          bindingsMbt += `  }\n`;
        } else {
          bindingsMbt += `  let res : ${retType} = ${funcName}(${argsStr})\n`;
        }
        
        params.forEach((p, idx) => {
          if (p.type === 'NapiBufferView') {
            bindingsMbt += `  p${idx}.is_alive = false\n`;
          }
        });

        bindingsMbt += `  set_${retType}(env, res)\n`;
        bindingsMbt += `}\n`;

        dispatcherCode += `    ${id} => ${wrapperName}(env, info)\n`;

        const tsArgs = params.map(p => {
          let t = p.type;
          if (t === 'Int' || t === 'Double') t = 'number';
          else if (t === 'Bool') t = 'boolean';
          else if (t === 'String') t = 'string';
          else if (t === 'Bytes' || t === 'NapiBufferView') t = 'Buffer';
          return `${p.name}: ${t}`;
        }).join(', ');
        
        let tsRet = retType;
        if (tsRet === 'Int' || tsRet === 'Double') tsRet = 'number';
        else if (tsRet === 'Bool') tsRet = 'boolean';
        else if (tsRet === 'String') tsRet = 'string';
        else if (tsRet === 'Bytes') tsRet = 'Buffer';
        else if (tsRet === 'Unit') tsRet = 'void';
        
        dts += `export function ${funcName}(${tsArgs}): ${tsRet};\n`;
      }
    }
  }

  if (hasErrors) {
    process.exit(1);
  }

  dispatcherCode += `    _ => { let _ = napi_throw_error(env, b"", b"Invalid function ID"); moonbit_dummy_napi_value() }\n  }\n}\n`;
  bindingsMbt += `\n${dispatcherCode}\n`;
  
  bindingsMbt += `\npub fn moonbit_napi_init(env : NapiEnv, exports : NapiValue) -> NapiValue {\n`;
  for (const {name, id} of exportedFuncs) {
    bindingsMbt += `  let func_${id} = Ref(moonbit_dummy_napi_value())\n`;
    bindingsMbt += `  let _ = moonbit_napi_create_func(env, b"${name}\\x00", ${id}, func_${id})\n`;
    bindingsMbt += `  let _ = napi_set_named_property(env, exports, b"${name}\\x00", func_${id}.val)\n`;
  }
  bindingsMbt += `  exports\n}\n`;

  const mbtOut = path.join(pkgDir, '_napi_bindings.mbt');
  const dtsOut = path.join(pkgDir, 'index.d.ts');

  if (isCheck) {
    let oldMbt = '', oldDts = '';
    if (fs.existsSync(mbtOut)) oldMbt = fs.readFileSync(mbtOut, 'utf-8');
    if (fs.existsSync(dtsOut)) oldDts = fs.readFileSync(dtsOut, 'utf-8');
    if (oldMbt !== bindingsMbt || oldDts !== dts) {
      console.error("[ERROR] Generated files are not up-to-date. Please run 'npm run generate'.");
      process.exit(1);
    }
  } else {
    fs.writeFileSync(mbtOut, bindingsMbt);
    fs.writeFileSync(dtsOut, dts);
    console.log(`Successfully generated _napi_bindings.mbt and index.d.ts`);
  }
}

main().catch(console.error);
